import { useCallback, useEffect, useState } from 'react';
import { apiDelete, apiGet, apiPatch, postFormData } from '../../shared/api.js';
const EMPTY = { category: 'GENERAL', title: '', content: '', pinned: false, popup: false };
export default function AdminNotices() {
  const [data, setData] = useState(null); const [page, setPage] = useState(0); const [form, setForm] = useState(EMPTY); const [editNo, setEditNo] = useState(null); const [files, setFiles] = useState([]); const [message, setMessage] = useState('');
  const load = useCallback(() => apiGet(`/api/admin/notices?page=${page}`).then(setData), [page]); useEffect(() => { load(); }, [load]);
  async function edit(no) { const item = await apiGet(`/api/admin/notices/${no}`); setForm(item); setEditNo(no); }
  async function save(e) { e.preventDefault(); const body = new FormData(); Object.entries(form).forEach(([k,v]) => body.append(k, String(v))); files.forEach((f) => body.append('contentImages', f)); const result = await postFormData(editNo ? `/api/admin/notices/${editNo}` : '/api/admin/notices', body); setMessage(result.message); setForm(EMPTY); setEditNo(null); setFiles([]); load(); }
  async function remove(no) { if (!confirm('삭제하시겠습니까?')) return; setMessage((await apiDelete(`/api/admin/notices/${no}`)).message); load(); }
  async function popup(item) { setMessage((await apiPatch(`/api/admin/notices/${item.noticeNo}/popup`, { popup: !item.popup })).message); load(); }
  return <><header className="page-header"><h1>공지 관리</h1></header>{message && <p className="message success">{message}</p>}<section className="panel admin-two-column"><form className="stack-form" onSubmit={save}><h2>{editNo ? '공지 수정' : '공지 등록'}</h2><select value={form.category} onChange={(e) => setForm({...form, category:e.target.value})}><option value="GENERAL">일반</option><option value="SYSTEM">시스템</option><option value="SERVICE">서비스</option></select><input value={form.title} onChange={(e) => setForm({...form,title:e.target.value})} placeholder="제목" required/><textarea rows="10" value={form.content} onChange={(e) => setForm({...form,content:e.target.value})} placeholder="내용" required/><label className="check-row"><input type="checkbox" checked={form.pinned} onChange={(e) => setForm({...form,pinned:e.target.checked})}/> 상단 고정</label><label className="check-row"><input type="checkbox" checked={form.popup} onChange={(e) => setForm({...form,popup:e.target.checked})}/> 메인 팝업</label><input type="file" multiple onChange={(e) => setFiles([...e.target.files])}/><button className="primary">저장</button>{editNo && <button type="button" onClick={() => {setEditNo(null);setForm(EMPTY);}}>취소</button>}</form><div className="simple-list">{data?.items.map((n) => <article key={n.noticeNo} className="admin-list-row"><div><strong>{n.title}</strong><small>{n.registeredDate}</small></div><div><button onClick={() => edit(n.noticeNo)}>수정</button><button onClick={() => popup(n)}>{n.popup?'팝업 해제':'팝업'}</button><button className="danger" onClick={() => remove(n.noticeNo)}>삭제</button></div></article>)}</div></section><div className="pager"><button disabled={data?.first} onClick={() => setPage(page-1)}>이전</button><button disabled={data?.last} onClick={() => setPage(page+1)}>다음</button></div></>;
}
