import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiGet } from '../../shared/api.js';
import ComplaintRow from './ComplaintRow.jsx';

const CATEGORIES = [['ALL', '전체'], ['PRAISE', '칭찬합니다'], ['COMPLAINT', '불편합니다'], ['LOST', '분실물 문의']];
const TITLES = { ALL: '전체 민원', PRAISE: '칭찬합니다', COMPLAINT: '불편합니다', LOST: '분실물 문의' };

export default function ComplaintList() {
  const [params, setParams] = useSearchParams(); const category = params.get('category') || 'ALL'; const keyword = params.get('keyword') || ''; const page = Number(params.get('page') || 0);
  const [keywordInput, setKeywordInput] = useState(keyword); const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [selected, setSelected] = useState(null); const [postPassword, setPostPassword] = useState(''); const [verifyError, setVerifyError] = useState(''); const [verifying, setVerifying] = useState(false);
  useEffect(() => { setKeywordInput(keyword); }, [keyword]);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); const query = new URLSearchParams({ category, keyword, page: String(page) }); fetch(`/api/public/complaints?${query}`, { signal: controller.signal }).then((response) => { if (!response.ok) throw new Error('민원 목록을 불러오지 못했습니다.'); return response.json(); }).then(setData).catch((reason) => { if (reason.name !== 'AbortError') setError(reason.message); }).finally(() => setLoading(false)); return () => controller.abort(); }, [category, keyword, page]);
  const update = (patch) => setParams({ category, keyword, page: '0', ...patch });
  function openComplaint(item) { setSelected(item); setPostPassword(''); setVerifyError(''); }
  async function verifyComplaint(event) { event.preventDefault(); if (!selected || verifying) return; setVerifying(true); setVerifyError(''); try { const csrf = await apiGet('/api/csrf', { redirectOnExpire: false }); const response = await fetch(`/complaints/${selected.complaintNo}/verify`, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/x-www-form-urlencoded', Accept: 'application/json', [csrf.headerName]: csrf.token }, body: new URLSearchParams({ password: postPassword }) }); const result = await response.json(); if (!response.ok || !result.success) throw new Error(result.message || '비밀번호를 확인하지 못했습니다.'); window.location.assign(result.redirectUrl); } catch (reason) { setVerifyError(reason.message); } finally { setVerifying(false); } }
  const start = Math.max(0, page - 4); const end = Math.min((data?.totalPages || 1) - 1, page + 4);

  return <><main id="complaint-board" className="board-page"><section className="board-intro"><h1>고객의 소리를 들려주세요</h1><span>칭찬과 불편사항, 분실물 문의를 남겨주시면 담당자가 확인하겠습니다.</span></section><section className="board-card" aria-label="민원 게시판">
    <div className="board-tools"><nav className="category-tabs" aria-label="민원 분류">{CATEGORIES.map(([value, label]) => <a key={value} href="#" className={category === value ? 'active' : ''} onClick={(event) => { event.preventDefault(); update({ category: value }); }}>{label}</a>)}</nav><form className="board-search" onSubmit={(event) => { event.preventDefault(); update({ keyword: keywordInput.trim() }); }}><label className="sr-only" htmlFor="board-keyword">제목 검색</label><input id="board-keyword" type="search" maxLength="100" value={keywordInput} onChange={(event) => setKeywordInput(event.target.value)} placeholder="제목 앞부분을 검색하세요" /><button type="submit" aria-label="검색"><svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5" /><path d="m15.5 15.5 5 5" /></svg></button></form></div>
    <div className="board-meta"><p><b>{TITLES[category]}</b> · 총 <strong>{data?.totalElements || 0}</strong>건</p><span>게시글 내용은 등록한 비밀번호 확인 후 볼 수 있습니다.</span></div>
    {loading && <p className="message">목록을 불러오는 중입니다.</p>}{error && <p className="message error">{error}</p>}{!loading && !error && data && <div className="board-table-wrap"><table className="board-table"><thead><tr><th>번호</th><th>분류</th><th>진행상황</th><th>제목</th><th>작성자</th><th>등록일</th></tr></thead><tbody>{data.items.map((item) => <ComplaintRow key={item.complaintNo} item={item} onOpen={openComplaint} />)}{!data.items.length && <tr><td className="empty-row" colSpan="6">검색 조건에 맞는 민원 게시글이 없습니다.</td></tr>}</tbody></table></div>}
    <div className="board-footer">{data && data.totalPages > 0 && <nav className="pagination" aria-label="페이지 이동"><a className={`page-arrow ${data.first ? 'disabled' : ''}`} href="#" onClick={(event) => { event.preventDefault(); if (!data.first) setParams({ category, keyword, page: String(page - 1) }); }}>‹</a>{Array.from({ length: end - start + 1 }, (_, i) => start + i).map((number) => <a key={number} className={number === page ? 'active' : ''} href="#" onClick={(event) => { event.preventDefault(); setParams({ category, keyword, page: String(number) }); }}>{number + 1}</a>)}<a className={`page-arrow ${data.last ? 'disabled' : ''}`} href="#" onClick={(event) => { event.preventDefault(); if (!data.last) setParams({ category, keyword, page: String(page + 1) }); }}>›</a></nav>}<Link className="write-button" to={`/complaints/new?category=${category === 'ALL' ? 'COMPLAINT' : category}`}>글쓰기</Link></div>
  </section></main>
  {selected && <div className="password-modal"><button type="button" className="modal-backdrop" aria-label="팝업 닫기" onClick={() => setSelected(null)} /><section className="password-dialog" role="dialog" aria-modal="true"><button className="dialog-close" type="button" onClick={() => setSelected(null)}>×</button><div className="password-icon">🔒</div><h2>게시글 비밀번호 확인</h2><p>{selected.title}</p><form onSubmit={verifyComplaint}><label htmlFor="post-view-password">비밀번호</label><input id="post-view-password" type="password" maxLength="20" autoComplete="current-password" placeholder="등록한 비밀번호를 입력하세요" required autoFocus value={postPassword} onChange={(event) => setPostPassword(event.target.value)} />{verifyError && <p className="password-message">{verifyError}</p>}<div className="dialog-actions"><button type="button" className="cancel-button" onClick={() => setSelected(null)}>취소</button><button type="submit" className="confirm-button" disabled={verifying}>{verifying ? '확인 중...' : '확인'}</button></div></form></section></div>}
  </>;
}
